### ISSUE TITLE
Automatic Passage Creation?

### ISSUE THREAD

**Issue by byronpendason** [rzel100/tweezel#1]
Is there a way to do automatic passage creation? I'm thinking of maybe when you exit a passage, it searches for links in double brackets, and creates an empty passage for it if there isn't already one?

Or, as an alternative, maybe a button somewhere on the main screen of the story that scans for links to passages that don't exist so you know that you need to create it? 

It's pretty easy to lose track of broken links when a story gets big enough, and I think implementing one of the two above features would make things a lot easier.

Other than that, I have no complaints about this app. It's excellent, thank you so much for the work you've put into this app!

**Comment by rzel100** [comment]
It is a useful idea. I'll keep an eye for that.
Maybe I'll make it a toggle ?. Like is it will auto generate the exit passage or just to give you a warning one.
Twine sure auto create the passage and notice it to the user. So maybe I'll do that.

Thanks for the idea. I'll add it to the to-do list.
And. Glad you like it. It is already in PlayStore with more feature than the web one so go check it out !.

**Comment by byronpendason** [comment]
> It is a useful idea. I'll keep an eye for that. Maybe I'll make it a toggle ?. Like is it will auto generate the exit passage or just to give you a warning one. Twine sure auto create the passage and notice it to the user. So maybe I'll do that.
> 
> Thanks for the idea. I'll add it to the to-do list. And. Glad you like it. It is already in PlayStore with more feature than the web one so go check it out !.

That's the one I use! I initially used the web app, until I discovered the Play Store yesterday.

**Comment by rzel100** [comment]
:) Done !.

It is on the way uploading to the Play Store. Thanks for the Idea :)

**Comment by byronpendason** [comment]
It doesn't recognize arrow links to new passages (such as `[[text->passage]]`), though it does to appear to recognize pipe usage (e.g., `[[text|passage]]`).

![Screenshot_20230825-154137](https://github.com/rzel100/tweezel/assets/22679696/678286f4-279d-4eb8-bad0-21cd733a2f28)

![Screenshot_20230825-154150](https://github.com/rzel100/tweezel/assets/22679696/7aad0e59-2ddd-42ac-933a-c380b96bf2b1)

**Comment by rzel100** [comment]
Sorry for that.
Actually it is also my fault for not including the detection of arrow passage links. Silly me for not noticing it.
Thanks to you. now I already updating the app so it will also detect the arrow passage links.

Thanks again for noticing it.

**Comment by byronpendason** [comment]
Tweezel is definitely the best Android app that I use, not many of them have developers that are so responsive. Thank you not only for the app itself, but also being so willing to listen to your app users. You are awesome!

**Comment by byronpendason** [comment]
So, I've discovered a new issue. It doesn't recognize functions in links. For example, `[[Restart->state.restart()]]` (to restart the game). Should be an easy fix. If you're using REGEX for your filter, you can just filter out `/\(.*\)$`. This will look for a set of parenthesis at the end of the string, with zero or any number of characters in between the parenthesis.

![Screenshot_20231024-130206-859](https://github.com/rzel100/tweezel/assets/22679696/6451ee69-217c-467f-8fd6-3278c772adbb)

**Comment by rzel100** [comment]
Yes... I Didn't Cover All Of That... I Never Know There Are These Links... If U Know Anymore Let Me Know...
And Yes... I Was In The Middle Of Something Here... My Work... So It Maybe Take Longer For Me To Continue... I'll Continue Developing TweezeL After My Work... Thanks For Letting Me Know...

**Comment by byronpendason** [comment]
I understand, work has to come first. I'm not worried about how long it takes, I'm just excited to be able to help make great software even better.

**Comment by rzel100** [comment]
It Is All Fixed... It Will Be Released Maybe At The End Of This Week... Also... Should I Put The Release On Github As Well...???

Also I Will Put A Toggle To On/Off This Feature... So... If It Acting Buggy You Can Disable It... And I Will Put It On "Experimental" Tag... It Is Can Be Used But Maybe Buggy... :) It Will Be Auto "On"...
