### ISSUE TITLE
Request: Passage Tags

### ISSUE THREAD

**Issue by byronpendason** [rzel100/tweezel#2]
I hope I'm not becoming bothersome, I just really enjoy this app. I was wondering if there's a way to use tags with passages. If not, can Twee style tags be added? By that, I mean adding tags in the title in between square brackets (for example, `Port [boat]`), and maybe an option to filter passages for those containing a specific tag?

I can think of a couple different uses for having tags.  The first usage that comes to mind is organization. If you're making an inventory system, for example, you can tag each passage in that system with `inventory`, and then filter out all other passages that aren't involved in that system. I've also noticed that some third party add-ons for Twine use tags.

Anyways, just an idea.

**Comment by rzel100** [comment]
Yes... True... It is a good idea...

Before I release TweezeL... I also think of to include Tags feature like in Twine... But to be honest... I never use it so I don't know the impact of using tags on the story... Maybe I'll think about it and will find out what tags do on the App... If they affect nothing on the app... It is might be easy to add the tags feature...

Thanks for the suggestion... I'll think about it for a while... then I'll decide should I do it or not...

**Comment by rzel100** [comment]
Sorry for taking so long... My job quite overwhelm me recently...
Anyway...

The tags also a core feature in Twine I guess... So it would be nice if TweezeL have one to setup...
The tags seems do not affect to much on code... So it maybe will done easily... But if I also want to make a filter passage with tags... Then it gonna take longer to code...

So... It is a good idea to add this "tags" feature... So I'll do it and I'll add to my to do list... Maybe take longer to develop... Thanks for the suggestion...

**Comment by byronpendason** [comment]
I thought of another use for tags. At least in SugarCube (I don't know a whole lot about the other story formats so I can't comment on them), some functionality requires having a passage with a specific tag. For example, it seems like you can't create widgets without marking a passage with the `widget` tag.

**Comment by rzel100** [comment]
Yes. It is alright. It is done.
It is now behave like Twine does. Kinda. It is how Twee implement it. So I think it will support any story formats.

Glad I done this. It is much challenges to me !.

Anyway. I cleaned up the code. I'll upload it to the playstore. Stay tuned a bit more. It will appear the update on playstore.
If u have any bugs or something to implement. Fell free to open issues !. :)

**Comment by byronpendason** [comment]
Just a few suggestions, with no pressure or rush implementing any of these:
- Would it be possible to show the tags on the story's main page? Maybe putting tags in square brackets twee style (for example: `Clearing [woods homearea]` where the passage is called "Clearing" and has the tags "woods" and "homearea")
- A tab in the Story settings listing all of the tags and an option to set a color for tags. If a color is set for a tag, the listing for any passages with that tag on the story's main page has its background color set to that color. In the case of passages having multiple tags, the background color is the color of the first tag that has a color assigned.
- A filter option on the story's main page to only show passages with specific tags, with an option to reset the filter to show all passages.

Again, these are just suggestions to make working with tags more efficient. This is already a great app without these suggestions being implemented, so I will definitely continue using it regardless of whether they get implemented.

**Comment by rzel100** [comment]
Yes. I'll consider it. Since there are nothing I could update. I mean I have no idea what should I add next so maybe I'll do it.
It is a cool idea and why not. Maybe it (I know I say it a lot but.) takes a while since I also working. But I'll update it when it done. I estimate it at the end of february.

Also thanks for keep using this app. Your suggestion is helping me out on what I should do with this project to prevent it from being abandoned.

**Comment by rzel100** [comment]
It is all done. You may use it. It is not tested that much but it is expected to work for Twine to TweezeL and vice versa. :)
