### ISSUE TITLE
Import/Export twee code?

### ISSUE THREAD

**Issue by byronpendason** [rzel100/tweezel#3]
I don't know what you use for the backend of Tweezel to compile the projects to HTML, but I know that some compilers let you import and/or export to twee code. If the compiler you use for a backend has this function, is there any way to add it to the Tweezel app? It'll make going from computer to phone and back a lot easier since the Twine app also lets you import and export twee code.

**Comment by maxiu250** [comment]
I have a project that is already halfway through and have only now discovered this tool. If I was able to import twine's twee (or html?), that would help me too much.

**Comment by rzel100** [comment]
Sorry it takes to long. It's been on my list to do since back then. You now can export and import twee files. :). Not tested on all kinds of twee files but enough to do export and import from Twine to TweezeL and vice versa. Thanks for suggestions. :)
